pool:
 vmImage: 'ubuntu-16.04'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'war'
    pathToPublish: '$(build.artifactStagingDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1 (397c23ce-ca49-488e-93a4-28fcec20c74e)'
        appType: 'webApp'
        WebAppName: 'SimpleWebAppBBDemo'
        packageForLinux: '/home/vsts/work/1/a/target/simpleWebApplication.1-0.0.1-SNAPSHOT.war'

