# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(1)(23c6c33b-0ea8-43d9-844f-670611a085dc)'
    appType: 'webAppLinux'
    WebAppName: 'simpleWebApplication'
    deployToSlotOrASE: true
    ResourceGroupName: 'simpleapplication11-rg'
    SlotName: 'production'
    packageForLinux: '/home/vsts/work/1/s/target/simpleWebApplication.1-0.0.1-SNAPSHOT.war'
    RuntimeStack: 'TOMCAT|8.5-jre8'
